version: '3.10'

services:
  django:
    image: django-docker_test:0.0.1
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./mysite:/app/mysite
    command: python manage.py runserver 0.0.0.0:8000